name: converter

on:
  push:
    branches:
      - master

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-20.04
    container:
      image: docker://pandoc/latex:2.9
      options: --entrypoint=sh
    steps:
      - uses: actions/checkout@v2
      - name: prepare output directories
        run: |
          shopt -s globstar
          for dir in ./**/docs/help/**;
          do
            if [ -d "$dir" ]; then
              mkdir -p output/$dir
              echo "making dir:"$dir
            fi
          done
        shell: bash
      - name: convert md to html
        run: |
          find ./ -iname '*.md' -type f -exec sh -c 'pandoc ${0} -o output/${0%.md}.html' {} \;
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: output
