name: converter

on:
  push:
    branches:
      - master

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-20.04
    container:
      image: docker://pandoc/latex:2.9
      options: --entrypoint=bash
    steps:
      - uses: actions/checkout@v2
      - name: output dir
        run: echo $(ls)
      - name: change perms
        run: chmod +x "test.sh"
      - name: prepare output directories
        run: test.sh
        shell: bash
      - name: convert md to html
        run: |
          find ./ -iname '*.md' -type f -exec sh -c 'pandoc ${0} -o output/${0%.md}.html' {} \;
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: output
