name: converter

on:
  push:
    branches:
      - master

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-20.04
    container:
      image: docker://pandoc/latex:2.9
      options: --entrypoint=bash
    steps:
      - uses: actions/checkout@v2
      - name: prepare output directories
        run: |
          find . -maxdepth 5 -type d -wholename './docs/help/*' -exec mkdir -p output/{} \;
      - name: convert md to html with mvp.css
        run: |
          find ./ -iname '*.md' -type f -exec sh -c 'pandoc -s ${0} -o output/${0%.md}.html' {} \;
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: output
