name: Receive documentation update trigger
# Receives a trigger from Constellation repository to update documentation.

on: [repository_dispatch]

jobs:
  rebuild-documentation:
    runs-on: ubuntu-20.04
    container:
      image: docker://pandoc/latex:2.9
      options: --entrypoint=bash
    steps:
      - name: get curl
        run: |
          apk update && apk add --no-cache coreutils && apk add bash && apk add git
      - name: Checkout GitHub Pages repository
        uses: actions/checkout@v2
        with:
          path: pages
      - name: Checkout Constellation repository
        uses: actions/checkout@v2
        with:
          repository: aldebaran30701/constellation
          path: ./constellation
          ref: documentation_update
      - name: remove old pages and make a new directory
        run: |
              rm -r ./pages/docs/help && mkdir -p ./pages/docs/help
      - name: add execute priveledge onto scripts
        run: |
              chmod +x ./constellation/toc_update.sh && chmod +x ./pages/.github/workflows/file_convert.sh && chmod +x ./pages/.github/workflows/file_copy.sh
      - name: update table of contents
        shell: bash
        run: |
            ./constellation/toc_update.sh
      - name: run file_convert
        shell: bash
        run: |
            ./pages/.github/workflows/file_convert.sh
      - name: run file_copy
        shell: bash
        run: |
            ./pages/.github/workflows/file_copy.sh
      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4.12.0
        with:
          repository: 'pages'
          commit_message: 'Documentation Update Automated'
          skip_fetch: true
          commit_options: '--no-verify'
          add_options: '.'
      - name: upload items
        uses: actions/upload-artifact@master
        with:
          name: upload pages
          path: ./pages/docs/help
