name: Receive documentation update trigger
# Receives a trigger from Constellation repository to update documentation.
# Sends a pong request to acknowledge that it has been received.

on: [repository_dispatch]

jobs:
  ping-pong:
    runs-on: ubuntu-20.04
    container:
      image: docker://pandoc/latex:2.9
      options: --entrypoint=bash
    steps:
      - name: get curl
        run: |
          apk update && apk add --no-cache coreutils && apk add curl && apk add bash && apk add tree && apk add git
      - name: Event Information
        run: |
          echo "Event '${{ github.event.action }}' received from '${{ github.event.client_payload.repository }}'"
      - name: PONG - Dispatch response to received PING
        if: github.event.action == 'ping'
        run: |
          curl -X POST https://api.github.com/repos/aldebaran30701/constellation/dispatches \
          -H 'Accept: application/vnd.github.v3+json' \
          -u ${{ secrets.ACCESS_TOKEN }} \
          --data '{"event_type": "pong", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'

      - name: Checkout GHPages
        uses: actions/checkout@v2
        with:
          path: pages

      - name: Checkout Constellation
        uses: actions/checkout@v2
        with:
          repository: aldebaran30701/constellation
          path: ./constellation
          ref: documentation_update

      - name: mkdir
        run: |
              mkdir -p ./pages/docs/help
      - name: chmod convert
        run: |
              chmod +x ./pages/.github/workflows/file_convert.sh
      - name: chmod copy
        run: |
              chmod +x ./pages/.github/workflows/file_copy.sh
      - name: tree
        run: |
              tree -f -L 4
      - name: run file_convert
        shell: bash
        run: |
            ./pages/.github/workflows/file_convert.sh


      - name: run file_copy
        shell: bash
        run: |
            ./pages/.github/workflows/file_copy.sh
      - name: Add & Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: GithubActions
          commit_author: GithubActions
          repository: './constellation'
          commit_message: 'Documentation Update Automated'
          skip_fetch: true
          skip_dirty_check: true
          add_options: '.'

      - name: tree after
        run: |
              tree -f -L 4
      - name: upload items
        uses: actions/upload-artifact@master
        with:
          name: upload pages
          path: ./pages/docs/help
